// <auto-generated />
namespace DancerWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dancer4445 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dancer4445));
        
        string IMigrationMetadata.Id
        {
            get { return "201806210923538_dancer4445"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
